name: AutoSave
main: net.milkbowl.autosave.AutoSave
version: 2.0.1
author: Morgan Humes aka Cereal, Xon
description: >
             Provides automatic world saves at defined intervals.  The focus
             of the plugin is to provide a method to flush changes to disk.

commands:
  autosave:
    description: Saves the world.
    aliases: save
